CREATE TABLE IF NOT EXISTS `ans3_assesmen_prasedasi_anestesi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `no_rawat` varchar(20) NOT NULL,
  `diagnosa_prabedah` text DEFAULT NULL,
  `rencana_tindakan` text DEFAULT NULL,
  `tipe_tindakan` enum('Elektif','Emergensi/CITO') DEFAULT NULL,
  
  `anamnese_dari` enum('Pasien','Keluarga pasien') DEFAULT NULL,
  `riwayat_anestesi` enum('Ada','Tidak') DEFAULT NULL,
  `riwayat_anestesi_ket` varchar(255) DEFAULT NULL,
  `komplikasi` varchar(255) DEFAULT NULL,
  `obat_sedang_dikonsumsi` text DEFAULT NULL,
  `riwayat_alergi` enum('Ada','Tidak') DEFAULT NULL,
  `riwayat_alergi_ket` varchar(255) DEFAULT NULL,
  
  `bb` varchar(20) DEFAULT NULL,
  `tb` varchar(20) DEFAULT NULL,
  `tanda_vital_td` text DEFAULT NULL,
  `tanda_vital_nadi` text DEFAULT NULL,
  `tanda_vital_rr` text DEFAULT NULL,
  `tanda_vital_suhu` text DEFAULT NULL,
  `tanda_vital_vas` text DEFAULT NULL,
  
  `bebas` enum('Ya','Tidak') DEFAULT NULL,
  `protusi_mandibula` enum('Ya','Tidak') DEFAULT NULL,
  `jarak_mentohyoid` enum('Normal','Tidak') DEFAULT NULL,
  `jarak_mentohyoid_ket` varchar(50) DEFAULT NULL,
  `jarak_thyrohyoid` enum('Pendek','Tidak') DEFAULT NULL,
  `jarak_thyrohyoid_ket` varchar(50) DEFAULT NULL,
  `buka_mulut` enum('Normal','Tidak') DEFAULT NULL,
  `mallampathy` enum('I','II','III','IV') DEFAULT NULL,
  `leher` enum('Pendek','Tidak') DEFAULT NULL,
  `gerak_leher` enum('Bebas','Tidak') DEFAULT NULL,
  `obesitas` enum('Ya','Tidak') DEFAULT NULL,
  `massa` enum('Ya','Tidak') DEFAULT NULL,
  `gigi_palsu` enum('Ya','Tidak') DEFAULT NULL,
  `sulit_ventilasi` enum('Ya','Tidak') DEFAULT NULL,
  
  `pernafasan_dbn` enum('Y','N') DEFAULT NULL,
  `pernafasan_asma` enum('Y','N') DEFAULT NULL,
  `pernafasan_pneumonia` enum('Y','N') DEFAULT NULL,
  `pernafasan_ispa` enum('Y','N') DEFAULT NULL,
  `pernafasan_tuberkulosis` enum('Y','N') DEFAULT NULL,
  `pernafasan_lainnya` varchar(100) DEFAULT NULL,
  `pernafasan_keterangan` text DEFAULT NULL,
  
  `kardiovaskular_dbn` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_ekg_abnormal` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_hipertensi` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_disritma` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_murmur` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_angina` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_pacemaker` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_chf` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_penyakit_katup` enum('Y','N') DEFAULT NULL,
  `kardiovaskular_lainnya` varchar(100) DEFAULT NULL,
  `kardiovaskular_keterangan` text DEFAULT NULL,
  
  `neuro_dbn` enum('Y','N') DEFAULT NULL,
  `neuro_sakit_kepala` enum('Y','N') DEFAULT NULL,
  `neuro_penurunan_kesadaran` enum('Y','N') DEFAULT NULL,
  `neuro_distropi` enum('Y','N') DEFAULT NULL,
  `neuro_parese` enum('Y','N') DEFAULT NULL,
  `neuro_parastesia` enum('Y','N') DEFAULT NULL,
  `neuro_plegi` enum('Y','N') DEFAULT NULL,
  `neuro_kejang` enum('Y','N') DEFAULT NULL,
  `neuro_lainnya` varchar(100) DEFAULT NULL,
  `neuro_keterangan` text DEFAULT NULL,
  
  `renal_endokrin_dbn` enum('Y','N') DEFAULT NULL,
  `renal_diabetes` enum('Y','N') DEFAULT NULL,
  `renal_tiroid` enum('Y','N') DEFAULT NULL,
  `renal_gagal_ginjal` enum('Y','N') DEFAULT NULL,
  `renal_lainnya` varchar(100) DEFAULT NULL,
  `renal_keterangan` text DEFAULT NULL,
  
  `hepato_dbn` enum('Y','N') DEFAULT NULL,
  `hepato_sirosis` enum('Y','N') DEFAULT NULL,
  `hepato_hepatitis` enum('Y','N') DEFAULT NULL,
  `hepato_obstruksi` enum('Y','N') DEFAULT NULL,
  `hepato_ikterus` enum('Y','N') DEFAULT NULL,
  `hepato_mual_muntah` enum('Y','N') DEFAULT NULL,
  `hepato_lainnya` varchar(100) DEFAULT NULL,
  `hepato_keterangan` text DEFAULT NULL,
  
  `lainnya_organ_dbn` enum('Y','N') DEFAULT NULL,
  `lainnya_neonat` enum('Y','N') DEFAULT NULL,
  `lainnya_geriatri` enum('Y','N') DEFAULT NULL,
  `lainnya_hamil` enum('Y','N') DEFAULT NULL,
  `lainnya_kanker` enum('Y','N') DEFAULT NULL,
  `lainnya_anemia` enum('Y','N') DEFAULT NULL,
  `lainnya_dehidrasi` enum('Y','N') DEFAULT NULL,
  `lainnya_merokok` enum('Y','N') DEFAULT NULL,
  `lainnya_alkohol` enum('Y','N') DEFAULT NULL,
  `lainnya_pendarahan` enum('Y','N') DEFAULT NULL,
  `lainnya_lainnya` varchar(100) DEFAULT NULL,
  `lainnya_organ_keterangan` text DEFAULT NULL,
  
  `lab_hb` text DEFAULT NULL,
  `lab_hct` text DEFAULT NULL,
  `lab_ct` text DEFAULT NULL,
  `lab_pt` text DEFAULT NULL,
  `lab_leukosit` text DEFAULT NULL,
  `lab_trombosit` text DEFAULT NULL,
  `lab_bt` text DEFAULT NULL,
  `lab_aptt` text DEFAULT NULL,
  `lab_ureum` text DEFAULT NULL,
  `lab_creatinin` text DEFAULT NULL,
  `lab_sgot` text DEFAULT NULL,
  `lab_sgpt` text DEFAULT NULL,
  `lab_albumin` text DEFAULT NULL,
  `lab_globulin` text DEFAULT NULL,
  `lab_bilirubin_direct` text DEFAULT NULL,
  `lab_bilirubin_indirect` text DEFAULT NULL,
  `lab_na` text DEFAULT NULL,
  `lab_k` text DEFAULT NULL,
  `lab_cl` text DEFAULT NULL,
  `lab_gds` text DEFAULT NULL,
  `lab_t3` text DEFAULT NULL,
  `lab_tsh` text DEFAULT NULL,
  `lab_t4` text DEFAULT NULL,
  `lab_pco2` text DEFAULT NULL,
  `lab_be` text DEFAULT NULL,
  `lab_po2` text DEFAULT NULL,
  `lab_sao2` text DEFAULT NULL,
  `lab_lainlain` text DEFAULT NULL,
  
  `penunjang_ekg` text DEFAULT NULL,
  `penunjang_radiologi` text DEFAULT NULL,
  `penunjang_lainlain` text DEFAULT NULL,
  `keterangan_lain` text DEFAULT NULL,
  
  `ps_asa` text DEFAULT NULL,
  `rencana_sedasi` text DEFAULT NULL,
  
  `instruksi_puasa` enum('Y','N') DEFAULT NULL,
  `instruksi_puasa_jam` text DEFAULT NULL,
  `instruksi_persiapan_darah` enum('Ya','Tidak') DEFAULT NULL,
  `instruksi_persiapan_darah_cc` text DEFAULT NULL,
  `instruksi_obat_dihentikan` text DEFAULT NULL,
  `instruksi_lain1` text DEFAULT NULL,
  `instruksi_lain2` text DEFAULT NULL,
  `instruksi_lain3` text DEFAULT NULL,
  `instruksi_lain4` text DEFAULT NULL,
  `instruksi_lain5` text DEFAULT NULL,
  
  `tanggal` date DEFAULT NULL,
  `jam` varchar(20) DEFAULT NULL,
  `dokter_nama` text DEFAULT NULL,
  
  PRIMARY KEY (`id`),
  KEY `no_rawat` (`no_rawat`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
