CREATE TABLE `mlite_penilaian_awal_keperawatan_gigi_igd` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `cara_datang` enum('Sendiri','Ambulans','Diantar Keluarga','Diantar Polisi') NOT NULL,
  `diantar_oleh` varchar(50) NOT NULL,
  `rujukan` enum('Tidak','Ya') NOT NULL,
  `rujukan_dari` enum('-','RS','Klinik','Puskesmas','Dokter') NOT NULL,
  `diagnosis_rujukan` varchar(100) NOT NULL,
  `jenis_kasus` enum('Kasus Gigi dan Mulut','Kasus Umum','Trauma','Non Trauma') NOT NULL,
  `asuransi` enum('Asuransi','Umum','BPJS') NOT NULL,
  `alamat_kontak` varchar(100) NOT NULL,
  `nama_pengantar` varchar(50) NOT NULL,
  `hub_dengan_pasien` varchar(30) NOT NULL,
  `sumber_data` enum('Auto Anamnesis','Allo Anamnesis','Pasien Anak (0- <18 tahun)','Pasien Dewasa (18-65 tahun)','Pasien Geriatri (>65 tahun)') NOT NULL,
  `triase` enum('Merah (ATS 1)','Kuning (ATS 2 / ATS 3)','Hijau (ATS 4 / ATS 5)','Hitam (DOA)') NOT NULL,
  `cara_masuk` enum('Jalan Kaki','Kursi Roda','Brankar','Digendong') NOT NULL,
  `jam_mulai_triase` time NOT NULL,
  `jam_selesai_triase` time NOT NULL,
  `petugas_triase` varchar(50) NOT NULL,
  `keluhan_utama` text NOT NULL,
  `riwayat_penyakit_sekarang` text NOT NULL,
  `penyakit_jantung` enum('Tidak Ada','Ada') NOT NULL,
  `hipertensi` enum('Tidak Ada','Ada') NOT NULL,
  `diabetes` enum('Tidak Ada','Ada') NOT NULL,
  `hepatitis` enum('Tidak Ada','Ada') NOT NULL,
  `haemophilia` enum('Tidak Ada','Ada') NOT NULL,
  `tuberculosis` enum('Tidak Ada','Ada') NOT NULL,
  `hiv_aids` enum('Tidak Ada','Ada') NOT NULL,
  `penyakit_lainnya` varchar(100) NOT NULL,
  `menular_tidak_menular` enum('-','Menular','Tidak Menular') NOT NULL,
  `alergi_obat` varchar(100) NOT NULL,
  `alergi_makanan` varchar(100) NOT NULL,
  `keadaan_umum` varchar(30) NOT NULL,
  `kesadaran` varchar(30) NOT NULL,
  `td` varchar(10) NOT NULL,
  `nadi` varchar(10) NOT NULL,
  `rr` varchar(10) NOT NULL,
  `suhu` varchar(10) NOT NULL,
  `saturasi` varchar(10) NOT NULL,
  `gol_darah` varchar(5) NOT NULL,
  `bb` varchar(10) NOT NULL,
  `tb` varchar(10) NOT NULL,
  `status_pernikahan` enum('Lajang','Menikah') NOT NULL,
  `cerai_tinggal_bersama` enum('ya','tidak','jelaskan') NOT NULL,
  `ket_cerai` varchar(50) NOT NULL,
  `riwayat_kebiasaan_merokok` enum('Tidak','Ya') NOT NULL,
  `riwayat_kebiasaan_alkohol` enum('Tidak','Ya') NOT NULL,
  `riwayat_kebiasaan_napza` enum('Tidak','Ya') NOT NULL,
  `riwayat_kebiasaan_lainnya` enum('Tidak','Ya') NOT NULL,
  `ket_riwayat_kebiasaan` varchar(50) NOT NULL,
  `hambatan_fisik_pendengaran` enum('Tidak','Ya') NOT NULL,
  `hambatan_fisik_bicara` enum('Tidak','Ya') NOT NULL,
  `hambatan_fisik_penglihatan` enum('Tidak','Ya') NOT NULL,
  `hambatan_kognitif` text NOT NULL,
  `dirawat_sesama_gender` enum('Ya','Tidak') NOT NULL,
  `pantangan_makanan` enum('Ya','Tidak') NOT NULL,
  `ket_pantangan_makanan` varchar(50) NOT NULL,
  `hari_dihindari_tindakan` enum('Ya','Tidak') NOT NULL,
  `ket_hari_dihindari` varchar(50) NOT NULL,
  `bahasa_digunakan` varchar(50) NOT NULL,
  `ekonomi` enum('Sangat Tinggi','Tinggi','Sedang','Rendah') NOT NULL,
  `mst_penurunan_bb` int(11) NOT NULL,
  `mst_asupan_makanan` int(11) NOT NULL,
  `mst_diagnosis_khusus` enum('Tidak','Ya') NOT NULL,
  `mst_total` int(11) NOT NULL,
  `strong_kurus` int(11) NOT NULL,
  `strong_penurunan_bb` int(11) NOT NULL,
  `strong_kondisi` int(11) NOT NULL,
  `strong_penyakit` int(11) NOT NULL,
  `asesmen_jatuh_a` enum('Ya','Tidak') NOT NULL,
  `asesmen_jatuh_b` enum('Ya','Tidak') NOT NULL,
  `asesmen_jatuh_hasil` varchar(50) NOT NULL,
  `asesmen_jatuh_tindakan_tidak` enum('Tidak','Ya') NOT NULL,
  `asesmen_jatuh_tindakan_edukasi` enum('Tidak','Ya') NOT NULL,
  `asesmen_jatuh_tindakan_kalung` enum('Tidak','Ya') NOT NULL,
  `asesmen_jatuh_tindakan_alat` enum('Tidak','Ya') NOT NULL,
  `asesmen_jatuh_tindakan_dampingi` enum('Tidak','Ya') NOT NULL,
  `pemeriksaan_penunjang_lab` enum('Tidak','Ya') NOT NULL,
  `pemeriksaan_penunjang_rontgen` enum('Tidak','Ya') NOT NULL,
  `pemeriksaan_penunjang_lainnya` enum('Tidak','Ya') NOT NULL,
  `ket_pemeriksaan_penunjang` varchar(100) NOT NULL,
  `masalah_keperawatan` text NOT NULL,
  `rencana_tindak_lanjut` text NOT NULL,
  `evaluasi_kontrol` enum('Tidak','Ya') NOT NULL,
  `evaluasi_kontrol_tgl` varchar(20) NOT NULL,
  `evaluasi_rujuk` enum('Tidak','Ya') NOT NULL,
  `evaluasi_rujuk_ke` varchar(50) NOT NULL,
  `evaluasi_rawat_inap` enum('Tidak','Ya') NOT NULL,
  `evaluasi_rawat_inap_ruangan` varchar(50) NOT NULL,
  `nip` varchar(20) NOT NULL,
  `nip_dpjp` varchar(20) NOT NULL,
  PRIMARY KEY (`no_rawat`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
